INSERT INTO supermarket(USERID, USERNAME,USERWORD) VALUES(AA, BB, 这里是对应的提醒他文件恶心特么普拉特
explate1
写入成功
)
INSERT INTO supermarket(USERID, USERNAME,USERWORD) VALUES(AA, BB, 这里是example2文件)
INSERT INTO supermarket(USERID, USERNAME,USERWORD) VALUES(AA, BB, 这里是relim3)
INSERT INTO supermarket(USERID, USERNAME,USERWORD) VALUES(AA, BB, 这里是relim4)
INSERT INTO supermarket(USERID, USERNAME,USERWORD) VALUES(AA, BB, 这里是js文件)
